//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirboxDemo.Resources.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AirboxDemo.Resources.Text.AppText", typeof(AppText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat.
        /// </summary>
        internal static string EnumSelectedPhotoTypeBoat {
            get {
                return ResourceManager.GetString("EnumSelectedPhotoTypeBoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        internal static string EnumSelectedPhotoTypeCar {
            get {
                return ResourceManager.GetString("EnumSelectedPhotoTypeCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helicopter.
        /// </summary>
        internal static string EnumSelectedPhotoTypeHelicopter {
            get {
                return ResourceManager.GetString("EnumSelectedPhotoTypeHelicopter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string EnumSelectedPhotoTypeNone {
            get {
                return ResourceManager.GetString("EnumSelectedPhotoTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        internal static string PhotoListPageHeading {
            get {
                return ResourceManager.GetString("PhotoListPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        internal static string PhotoViewPageHeading {
            get {
                return ResourceManager.GetString("PhotoViewPageHeading", resourceCulture);
            }
        }
    }
}
